// Writes the Motion spring presets (js/motion-tokens.js) into css/motion.css as CSS easings, so CSS
// animations and Motion animations share the exact same curves.
//   node scripts/springs.mjs
// tests/motion-tokens.test.js fails if the two ever drift apart.
import { readFile, writeFile } from 'node:fs/promises';
import { presets, cssSpring } from '../js/motion-tokens.js';

const FILE = new URL('../css/motion.css', import.meta.url);
const START = '/* springs:start (generated by scripts/springs.mjs from js/motion-tokens.js, do not edit) */';
const END = '/* springs:end */';

export function springBlock() {
  const lines = [];
  for (const name of ['tap', 'fast', 'default', 'expressive']) {
    const { duration, easing } = cssSpring(name);
    lines.push(`  --spring-${name}-dur: ${duration}ms;`, `  --spring-${name}: ${easing};`);
  }
  lines.push(`  --fade-dur: ${presets.fade.duration * 1000}ms;`, '  --fade: cubic-bezier(0, 0, 0.58, 1);');
  return `${START}\n:root {\n${lines.join('\n')}\n}\n${END}`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const css = await readFile(FILE, 'utf8');
  const block = springBlock();
  const re = /\/\* springs:start[\s\S]*?\/\* springs:end \*\//;
  await writeFile(FILE, re.test(css) ? css.replace(re, block) : css.trimEnd() + '\n' + block + '\n');
  console.log('css/motion.css springs updated');
}
